version: 2.1

workflows:
  test-env-vars:
    jobs:
      - build:
          context: Polaris

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    steps:
      - checkout
      - run:
          name: Polaris scan
          command: |
            curl -fsLOS $POLARIS_SERVER_URL/api/tools/polaris_cli-linux64.zip
            unzip -j polaris_cli-linux64.zip -d /tmp
            /tmp/polaris setup --project-name chuckaude-hello-java -e shell="mvn -B clean" -b shell="mvn -B package -DskipTests"
            /tmp/polaris analyze -w
