# Example workflow for Coverity on private self-hosted runners

name: Coverity private runner
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  coverity:

    runs-on: self-hosted

    env:
      COVBIN: /opt/coverity/analysis/current/bin
      COVERITY_SERVER_URL: https://coverity.chuckaude.com:8443/
      COVERITY_STREAM: hello-java-master
      COV_USER: committer
      COVERITY_PASSPHRASE: ${{ secrets.COVERITY_PASSPHRASE }}
      BLDCMD: mvn -B clean compile
      CHECKERS: --webapp-security

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Coverity BAC
      run: |
        env | sort
        rm -rf idir
        $COVBIN/cov-build --dir idir $BLDCMD
        $COVBIN/cov-analyze --dir idir --ticker-mode none --strip-path $PWD $CHECKERS
        $COVBIN/cov-commit-defects --dir idir --ticker-mode none --url $COVERITY_SERVER_URL --stream $COVERITY_STREAM
