# Example workflow for Polaris on private self-hosted runners

name: Polaris private runner
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  polaris:

    runs-on: self-hosted

    env:
      POLARIS_SERVER_URL:  https://sipse.polaris.synopsys.com/
      POLARIS_ACCESS_TOKEN:  ${{ secrets.POLARIS_ACCESS_TOKEN }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Polaris setup
      run: /opt/polaris/bin/polaris setup -p chuckaude-hello-java -e shell='mvn -B clean' -b shell='mvn -B compile'
    - name: Polaris scan
      run: /opt/polaris/bin/polaris analyze -w
