pool:
  name: private-windows

variables:
- group: coverity-onprem
- name: COVERITY_TOOL_HOME
  value: c:/tools/coverity/analysis/2020.09
- name: COVERITY_PROJECT
  value: hello-java

workspace:
  clean: all

steps:
- task: synopsys-coverity.synopsys-coverity-azure-devops.coverity-task.synopsys-coverity@1
  displayName: 'Coverity Analysis'
  inputs:
    coverityService: 'coverity-onprem'
    projectName: '$(COVERITY_PROJECT)'
    streamName: '$(COVERITY_PROJECT)-$(Build.SourceBranchName)'
    checkIssues: true
    issueView: 'Newly Detected Issues'
    issueStatus: 'unstable'
    buildCommand: 'mvn -B package -DskipTests'
    customCommandArgs: true
    covBuildArgs: '--fs-capture-search $(Build.SourcesDirectory)'
    covAnalyzeArgs: '--ticker-mode none --strip-path $(Build.SourcesDirectory) --webapp-security'
    covCommitArgs: '--ticker-mode none --description $(Build.BuildURI) --version $(Build.SourceVersion) --scm git'
    allowUntrusted: true
