variables:
  - group: Polaris
  - name: project
    value: 'chuckaude-hello-java'

jobs:
- job: Polaris
  pool:
    vmImage: vs2017-win2016
  workspace:
    clean: all
  steps:
  - task: CmdLine@2
    displayName: setup
    inputs:
      script: |
        curl -fsLOS %POLARIS_SERVER_URL%/api/tools/polaris_cli-win64.zip
        unzip -j polaris_cli-win64.zip -d .
        polaris setup --project-name $(project) -e shell="mvn -B clean" -b shell="mvn -B package -DskipTests"
  - task: CmdLine@2
    displayName: analyze
    inputs:
      script: 'polaris analyze -w'
